package 'git'
package 'fd'
package 'peco'
package 'ripgrep'
package 'starship'
package 'tbls'
package 'tfenv'
package 'tflint'
package 'tfmigrate'
package 'tig'
package 'trivy'
package 'nodenv'
package 'ghq'
package 'gh'
execute "brew install mutagen-io/mutagen/mutagen"
execute "brew install mutagen-io/mutagen/mutagen-compose"
package 'yamlfmt'
